-- MySQL Script generated by MySQL Workbench
-- Thu Aug 23 01:14:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Cadastro_Cliente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cadastro_Cliente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cadastro_Cliente` DEFAULT CHARACTER SET utf8 ;
USE `Cadastro_Cliente` ;

-- -----------------------------------------------------
-- Table `Cadastro_Cliente`.`tb_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cadastro_Cliente`.`tb_endereco` (
  `cod_endereco` INT NOT NULL AUTO_INCREMENT,
  `rua_endereco` VARCHAR(150) NULL,
  `bairro_endereco` VARCHAR(50) NULL,
  `cidade_endereco` VARCHAR(50) NULL,
  `numero_endereco` VARCHAR(20) NULL,
  `cep_endereco` INT(8) NULL,
  `complemento_endereco` VARCHAR(50) NULL,
  PRIMARY KEY (`cod_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadastro_Cliente`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cadastro_Cliente`.`tb_cliente` (
  `cod_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(255) NULL,
  `cnpj_cliente` VARCHAR(14) NULL,
  `uf_cliente` VARCHAR(2) NULL,
  `cod_endereco` INT NOT NULL,
  PRIMARY KEY (`cod_cliente`, `cod_endereco`),
  INDEX `fk_Cliente_Endereco1_idx` (`cod_endereco` ASC),
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`cod_endereco`)
    REFERENCES `Cadastro_Cliente`.`tb_endereco` (`cod_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadastro_Cliente`.`tb_responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cadastro_Cliente`.`tb_responsavel` (
  `cod_responsavel` INT NOT NULL AUTO_INCREMENT,
  `nome_responsavel` VARCHAR(255) NULL,
  `cpf_responsavel` VARCHAR(11) NULL,
  `cod_cliente` INT NOT NULL,
  PRIMARY KEY (`cod_responsavel`, `cod_cliente`),
  INDEX `fk_Responsavel_Cliente_idx` (`cod_cliente` ASC),
  CONSTRAINT `fk_Responsavel_Cliente`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `Cadastro_Cliente`.`tb_cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadastro_Cliente`.`tb_email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cadastro_Cliente`.`tb_email` (
  `cod_email` INT NOT NULL AUTO_INCREMENT,
  `endereco_email` VARCHAR(100) NULL,
  `cod_cliente` INT NOT NULL,
  PRIMARY KEY (`cod_email`, `cod_cliente`),
  INDEX `fk_email_cliente1_idx` (`cod_cliente` ASC),
  CONSTRAINT `fk_email_cliente1`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `Cadastro_Cliente`.`tb_cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cadastro_Cliente`.`tb_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cadastro_Cliente`.`tb_telefone` (
  `cod_telefone` INT NOT NULL AUTO_INCREMENT,
  `numero_telefone` VARCHAR(45) NULL,
  `cod_cliente` INT NOT NULL,
  PRIMARY KEY (`cod_telefone`, `cod_cliente`),
  INDEX `fk_telefone_cliente1_idx` (`cod_cliente` ASC),
  CONSTRAINT `fk_telefone_cliente1`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `Cadastro_Cliente`.`tb_cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





